inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - 'Rakefile'

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%i': '[]'

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  Enabled: false

Style/TrailingComma:
  Enabled: false
