language: ruby
sudo: false
rvm:
  - 2.3.3
  - 2.4.0
  - ruby-head
before_install:
  - gem update --system # https://github.com/rubygems/rubygems/pull/1819
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
