language: ruby
sudo: false
rvm:
  - 2.3.4
  - 2.4.1
  - ruby-head
before_install:
  - gem update --system # https://github.com/rubygems/rubygems/pull/1819
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
